### ISSUE TITLE
No support for testnet/testnet3

### ISSUE THREAD

**Issue by danaki** [ladimolnar/BitcoinBlockchain#1]
Just gives

```
InvalidBlockchainContentException: Invalid block Id: 709110B. Expected: D9B4BEF9
```

If any other blockchain used. Please consider a setting in constructor or similar solution.

**Comment by ladimolnar** [comment]
Hello danaki,

Thank you for your note. 

The “block Id” is a 32 bit constant that is present at the beginning of each Bitcoin block. It is there to allow a parser to confirm that it was able to correctly follow the blocks structure and that it does not attempt to read a block starting at an incorrect position. An error like the one you describe could occur for two reasons:
1. The value for “block Id” is D9B4BEF9 but some blocks in the test blockchain contain information in a format that is different from the one than the parser expects. If testnet / testnet3 have blocks with an unexpected format then eventually the parser  may end up attempting to process a block from the wrong position in the blockchain stream. As soon as that happens the parser will pick up a block that has for the “block Id” a value different than the one expected. That allows the parser to detect that it is “off” the correct course.
2. The value for “block Id” on testnet / testnet3 is different from the standard value of D9B4BEF9. This is the scenario where your suggestion is worth implementing.

I suspect that what you see is the scenario described at point 1. Having the parser stumble over a block that has an unexpected “block Id” strongly suggests that the parser does not process correctly the information in the previous block. Maybe it is possible but I’d be surprised if testnet / testnet3 simply use a different value for the “block Id”. 

Do you know for which block do you see that error? Is the error occurring in the very first block being processed? Or is the error occurring later in the processing? Can you point to some documentation indicating that the value for “magic Id” on testnet / testnet3 is 709110B?

**Comment by danaki** [comment]
I guess it was very first block of testnet3. Just try to feed testnet3 blockchain to BitcoinDatabaseGenerator to reproduce.

**Comment by ladimolnar** [comment]
I have little time and I won’t be able to switch to testnet / testnet3. It would be great if you can help by providing me with the first and last blockchain file generated with testnet / testnet3. If you do that I can take a closer look and confirm that the issue is indeed with the blockId and not with the way the data is stored in a block. 

If you give me an email I will share with you a dropbox link and then you can copy those files there. 

Thanks

**Comment by danaki** [comment]
Ok, blk00000.dat https://www.dropbox.com/s/1146k2o0or6vda7/blk00000.dat?dl=0
and blk00024.dat https://www.dropbox.com/s/f2iivu8wblqdhwc/blk00024.dat?dl=0

**Comment by ladimolnar** [comment]
Thank you danaki. You were right, the block Id has a different value in the files you provided. I will check-in a fix soon and will propagate the changes to the NuGet package as well. I will also cascade the changes in BitcoinDatabaseGenerator where I will add another command line parameter to expose this to a user that does not compile the sources.

**Comment by ladimolnar** [comment]
Support was added for scenarios where BlockId has a value that is different from the standard value of 0xD9B4BEF9. 

A new API method was added to interface IBlockchainParser and class BlockchainParser:  

```
void SetBlockId(UInt32 blockId);
```

This functionality was propagated to BitcoinDatabaseGenerator where we now have a new command line parameter: `/BlockId`. See BitcoinDatabaseGenerator [Release V 1.4](https://github.com/ladimolnar/BitcoinDatabaseGenerator/releases/tag/v1.4)
